[2024-11-02T21:29:16.220+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: table_dag.submit_tables scheduled__2024-09-20T00:00:00+00:00 [queued]>
[2024-11-02T21:29:16.379+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: table_dag.submit_tables scheduled__2024-09-20T00:00:00+00:00 [queued]>
[2024-11-02T21:29:16.381+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-02T21:29:16.631+0000] {taskinstance.py:1380} INFO - Executing <Task(PinotTableSubmitOperator): submit_tables> on 2024-09-20 00:00:00+00:00
[2024-11-02T21:29:16.731+0000] {standard_task_runner.py:57} INFO - Started process 12628 to run task
[2024-11-02T21:29:16.961+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'table_dag', 'submit_tables', 'scheduled__2024-09-20T00:00:00+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/table_dag.py', '--cfg-path', '/tmp/tmpvnz_swas']
[2024-11-02T21:29:17.027+0000] {standard_task_runner.py:85} INFO - Job 207: Subtask submit_tables
[2024-11-02T21:29:18.930+0000] {task_command.py:415} INFO - Running <TaskInstance: table_dag.submit_tables scheduled__2024-09-20T00:00:00+00:00 [running]> on host f79a3875bd34
[2024-11-02T21:29:20.139+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ctwang' AIRFLOW_CTX_DAG_ID='table_dag' AIRFLOW_CTX_TASK_ID='submit_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-09-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-20T00:00:00+00:00'
[2024-11-02T21:29:20.228+0000] {pinot_table_operator.py:35} ERROR - An error occurred: HTTPConnectionPool(host='pinot-controller', port=9000): Max retries exceeded with url: /tables (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f21fcd9fb80>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-11-02T21:29:20.347+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=table_dag, task_id=submit_tables, execution_date=20240920T000000, start_date=20241102T212916, end_date=20241102T212920
[2024-11-02T21:29:20.645+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-02T21:29:21.349+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
