[2024-11-02T21:28:43.835+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: table_dag.submit_tables scheduled__2024-09-22T00:00:00+00:00 [queued]>
[2024-11-02T21:28:50.734+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: table_dag.submit_tables scheduled__2024-09-22T00:00:00+00:00 [queued]>
[2024-11-02T21:28:50.989+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-02T21:28:55.059+0000] {taskinstance.py:1380} INFO - Executing <Task(PinotTableSubmitOperator): submit_tables> on 2024-09-22 00:00:00+00:00
[2024-11-02T21:28:55.886+0000] {standard_task_runner.py:57} INFO - Started process 12597 to run task
[2024-11-02T21:28:56.387+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'table_dag', 'submit_tables', 'scheduled__2024-09-22T00:00:00+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/table_dag.py', '--cfg-path', '/tmp/tmphn6cnkmc']
[2024-11-02T21:28:56.459+0000] {standard_task_runner.py:85} INFO - Job 210: Subtask submit_tables
[2024-11-02T21:28:59.829+0000] {task_command.py:415} INFO - Running <TaskInstance: table_dag.submit_tables scheduled__2024-09-22T00:00:00+00:00 [running]> on host f79a3875bd34
[2024-11-02T21:29:05.377+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ctwang' AIRFLOW_CTX_DAG_ID='table_dag' AIRFLOW_CTX_TASK_ID='submit_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-22T00:00:00+00:00'
[2024-11-02T21:29:05.696+0000] {pinot_table_operator.py:35} ERROR - An error occurred: HTTPConnectionPool(host='pinot-controller', port=9000): Max retries exceeded with url: /tables (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f21fcc678e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-11-02T21:29:05.794+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=table_dag, task_id=submit_tables, execution_date=20240922T000000, start_date=20241102T212843, end_date=20241102T212905
[2024-11-02T21:29:06.183+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-02T21:29:07.351+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
