[2024-11-02T21:28:39.776+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: table_dag.submit_tables scheduled__2024-09-25T00:00:00+00:00 [queued]>
[2024-11-02T21:28:39.844+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: table_dag.submit_tables scheduled__2024-09-25T00:00:00+00:00 [queued]>
[2024-11-02T21:28:39.850+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-02T21:28:40.098+0000] {taskinstance.py:1380} INFO - Executing <Task(PinotTableSubmitOperator): submit_tables> on 2024-09-25 00:00:00+00:00
[2024-11-02T21:28:40.183+0000] {standard_task_runner.py:57} INFO - Started process 12580 to run task
[2024-11-02T21:28:40.231+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'table_dag', 'submit_tables', 'scheduled__2024-09-25T00:00:00+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/table_dag.py', '--cfg-path', '/tmp/tmplxe8trtt']
[2024-11-02T21:28:40.527+0000] {standard_task_runner.py:85} INFO - Job 208: Subtask submit_tables
[2024-11-02T21:28:41.708+0000] {task_command.py:415} INFO - Running <TaskInstance: table_dag.submit_tables scheduled__2024-09-25T00:00:00+00:00 [running]> on host f79a3875bd34
[2024-11-02T21:28:43.071+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ctwang' AIRFLOW_CTX_DAG_ID='table_dag' AIRFLOW_CTX_TASK_ID='submit_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-25T00:00:00+00:00'
[2024-11-02T21:28:43.376+0000] {pinot_table_operator.py:35} ERROR - An error occurred: HTTPConnectionPool(host='pinot-controller', port=9000): Max retries exceeded with url: /tables (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f21fcc609d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-11-02T21:28:43.538+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=table_dag, task_id=submit_tables, execution_date=20240925T000000, start_date=20241102T212839, end_date=20241102T212843
[2024-11-02T21:28:43.843+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-02T21:28:54.101+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
